  eureka:
    instance:
      prefer-ip-address: true
    client:
      fetch-registry: true
      registry-with_eureka: true
      service-url:
        defaultzone: ${EUREKA_SERVER_ADDRESS:https//localhost:8761/eureka}
